"""removed category from applog

Revision ID: 418f1db2af50
Revises: 26825ef90789
Create Date: 2023-05-18 11:48:34.596931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '418f1db2af50'
down_revision = '26825ef90789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applog', schema=None) as batch_op:
        batch_op.drop_column('event_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_category', mysql.VARCHAR(length=16), nullable=True))

    # ### end Alembic commands ###
