"""renamed alias field in location table to short_name

Revision ID: 63c1270cd829
Revises: 418f1db2af50
Create Date: 2023-05-24 13:11:31.955143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63c1270cd829'
down_revision = '418f1db2af50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(length=8), nullable=True))
        batch_op.drop_index('ix_locations_alias')
        batch_op.create_index(batch_op.f('ix_locations_short_name'), ['short_name'], unique=True)
        batch_op.drop_column('alias')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', mysql.VARCHAR(length=8), nullable=True))
        batch_op.drop_index(batch_op.f('ix_locations_short_name'))
        batch_op.create_index('ix_locations_alias', ['alias'], unique=False)
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
