"""user role not nullable

Revision ID: 68da3f705c70
Revises: 2dd3496861c1
Create Date: 2023-04-17 17:07:14.641382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68da3f705c70'
down_revision = '2dd3496861c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('superadmin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('superadmin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
