"""added log table

Revision ID: 732d4f956c43
Revises: 3f23db8439c1
Create Date: 2023-05-18 11:03:02.362005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732d4f956c43'
down_revision = '3f23db8439c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('event_detail', sa.String(length=512), nullable=True),
    sa.Column('event_category', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applog')
    # ### end Alembic commands ###
