"""revert

Revision ID: 96646d10991a
Revises: d3cb86d88b84
Create Date: 2023-06-06 14:10:49.253470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96646d10991a'
down_revision = 'd3cb86d88b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount_limit', sa.Integer(), nullable=True))
        batch_op.drop_column('Minimum stock')
        batch_op.drop_column('Amount in Warehouse')
        batch_op.drop_column('Amount in Lab')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Amount in Lab', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Amount in Warehouse', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Minimum stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('amount_limit')
        batch_op.drop_column('amount2')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
