"""back to previous model

Revision ID: cd48413c4454
Revises: e0d52a79ab75
Create Date: 2023-04-28 11:59:16.928051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd48413c4454'
down_revision = 'e0d52a79ab75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_movement')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.drop_column('location_id')
        batch_op.drop_column('amount')
        batch_op.drop_column('amount2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('products_ibfk_1', 'locations', ['location_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_products_name'))

    op.create_table('product_movement',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('movement_date', sa.DATE(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('from_location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('to_location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('time_created', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], name='product_movement_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_movement_ibfk_2'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], name='product_movement_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
