"""new labels for inventory

Revision ID: d3cb86d88b84
Revises: 63c1270cd829
Create Date: 2023-06-06 14:08:22.973309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3cb86d88b84'
down_revision = '63c1270cd829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Amount in Lab', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Amount in Warehouse', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Minimum stock', sa.Integer(), nullable=True))
        batch_op.drop_column('amount')
        batch_op.drop_column('amount_limit')
        batch_op.drop_column('amount2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('Minimum stock')
        batch_op.drop_column('Amount in Warehouse')
        batch_op.drop_column('Amount in Lab')

    # ### end Alembic commands ###
